dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  #- export CXX=/usr/local/clang-5.0.0/bin/clang
  #- export CC=/usr/local/clang-5.0.0/bin/clang
  - export CXX=/usr/bin/g++-5 
  - export CC=/usr/bin/gcc-5
  - ls
  - cd cryptoTools/thirdparty/linux
  - bash all.get
  - cd ../../..
  - cmake .
  - cmake --build . -- -j2
